<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>action_bridge</name>
  <version>0.1.0</version>
  <description>UE Audio action bridge</description>

  <maintainer email="nschmitz@techfak.uni-bielefeld.de">Niklas Schmitz</maintainer>

  <license>Apache License 2.0</license>

  <author email="nschmitz@techfak.uni-bielefeld.de">Niklas Schmitz</author>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 dependencies -->
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>

  <!-- ROS 1 dependencies -->
  <depend>actionlib</depend>
  <depend>audio_common_msgs</depend>
  <depend>roscpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
